apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: gamelink
spec:
  selector:
    matchLabels:
      app: gamelink
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gamelink
    spec:
      containers:
      - image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        - "--group_concat_max_len=4194304"
        - "--max_allowed_packet=4194304"
        - "--sql-mode="
        name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
#        - name: MYSQL_ROOT_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: gamelink
#              key: MYSQLROOTPASSWORD
        - name: MYSQL_DATABASE
#          value: gamelink
          valueFrom:
            configMapKeyRef:
              name: gamelink-config
              key: MYSQLDATABASE
        - name: MYSQL_USER
#          value: gamelink
          valueFrom:
             configMapKeyRef:
               name: gamelink-config
               key: MYSQLUSERNAME
        - name: MYSQL_PASSWORD
#          value: password
          valueFrom:
            secretKeyRef:
               name: gamelink-secret
               key: MYSQLPASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: gamelink-mysql-pvc