apiVersion: v1
kind: Secret
metadata:
  name: gamelink-secret
type: Opaque
data:
  FBAPPSEC: ZmU5NzU5OWFlMjA3YmNkNjljYjEyMGRkNjA1YzRmMGY=
  VKAPPSEC: UkdjU0ZoeGJpNlFnRmNJN21aU3Y=
  MYSQLPASSWORD: MTIzCg==
  TAPASSWORD: cGFzc3dvcmQ=
#  REDISPWD=: cGFzc3dvcmQ=
