apiVersion: v1
kind: Service
metadata:
  labels:
    app: gamelink
  name: gamelink
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
#    newPort
  - name: grpc
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: gamelink
