apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc
  labels:
    component: grpc
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: grpc
    spec:
      containers:
        - image: grpc/go:latest
          name: grpc
          ports:
            - containerPort: 7777
              name: grpc