apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nats
  labels:
    component: nats
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
        - image: nats:latest
          name: nats
          ports:
            - containerPort: 4222
              name: nats